version: '3'

services:
    adminer:
        container_name: "stack_adminer"
        image: adminer
        restart: always
        ports:
            - "8080:8080"
    postgres:
        container_name: "stack_pg"
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '15432:5432'
        volumes:
            - db:/var/lib/postgresql/data
    php:
        container_name: "stack_php"
        build:
            context: ./php
        depends_on:
            - postgres
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
        volumes:
            - ${APP_FOLDER}:/var/www

    nginx:
        container_name: "stack_nginx"
        build:
            context: ./nginx
        volumes:
            - ${APP_FOLDER}:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./logs:/var/log
        depends_on:
            - php
        ports:
            - "80:80"
volumes:
    db:
        driver: local
